// <auto-generated />
using EmployeeManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagementSystemAPI.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20241010174451_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeManagementSystemAPI.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Malik",
                            LastName = "Azeem",
                            MiddleName = "Fahad"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Chris",
                            LastName = "Angel",
                            MiddleName = "John"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ali",
                            LastName = "Usman",
                            MiddleName = "Ahmed"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Overton",
                            LastName = "Watson",
                            MiddleName = "Shane"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Prem",
                            LastName = "Kumar",
                            MiddleName = "Lalit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
